DROP TABLE IF EXISTS default_accounts;
DROP TABLE IF EXISTS saving_accounts;

CREATE TABLE default_accounts (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  money DECIMAL(20, 2) NOT NULL,
  CAN_WITHDRAW BOOLEAN NOT NULL
);

CREATE TABLE saving_accounts (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  money DECIMAL(20, 2) NOT NULL,
  CAN_WITHDRAW BOOLEAN DEFAULT FALSE
);